# Generated by Django 4.2 on 2023-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRealtorBrokerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungu', models.CharField(blank=True, max_length=300, null=True)),
                ('city_code', models.CharField(max_length=20)),
                ('last_update_date', models.CharField(blank=True, max_length=30, null=True)),
                ('broker_asort_cd', models.CharField(blank=True, max_length=5, null=True)),
                ('broker_asort_nm', models.CharField(blank=True, max_length=20, null=True)),
                ('certi_no', models.CharField(blank=True, max_length=50, null=True)),
                ('certi_date', models.CharField(blank=True, max_length=50, null=True)),
                ('position_cd', models.CharField(blank=True, max_length=50, null=True)),
                ('position_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('jurirno', models.CharField(blank=True, max_length=100, null=True)),
                ('office_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('brk_nm', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'land_realtor_broker_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandRealtorOfficeList',
            fields=[
                ('sigungu', models.CharField(blank=True, max_length=300, null=True)),
                ('city_code', models.CharField(max_length=20)),
                ('last_update_date', models.CharField(blank=True, max_length=30, null=True)),
                ('jurirno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('office_nm', models.CharField(max_length=200)),
                ('brk_nm', models.CharField(max_length=200)),
                ('status_cd', models.CharField(blank=True, max_length=5, null=True)),
                ('status_nm', models.CharField(blank=True, max_length=30, null=True)),
                ('regist_date', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('establish_begin_date', models.CharField(blank=True, max_length=20, null=True)),
                ('establish_end_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'land_realtor_office_list',
                'managed': False,
            },
        ),
    ]
